---
title: "Homework 1"
author: "Helene, Rui, Hong"
date: "September 12, 2016"
output: 
  html_document:
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 2 

### Question 3 

### Question 4 : Major League Baseball

####i) Summarize the data by providing suitable summary statistics and graphs. Write a brief report for your findings.

#####Load and examine dataset:
paydata <- read.csv("MLPayData_Total.csv")
names(paydata)

#####select the variables we are interested in: team names, team total payroll from 1998 to 2014 (in billions), fraction of games won from 1998 to 2014, and payroll (in millions) and fraction of games won for the years we want to examine:  
paydata1 <- paydata[,c(3,1:2,4,54,12,46,20,38)]
head(paydata1)

#####rename the variables to more intelligible names: 
names(paydata1) <- c("team","tot.payroll","avgwin","payroll.1998","pctwin.1998","payroll.2006","pctwin.2006","payroll.2014","pctwin.2014")
head(paydata1)

#####create a vector of the mean of each variable, beside team 
tot.mean <- apply(X = paydata1[,-1], MARGIN = 2, FUN = mean)

#####create tot.mean row with the mean for all variables............. work in progress.................. it's not working!!!!!!! 
team <- "tot.mean"
tot.mean <- rbind(team, tot.mean)

paydata2 <- rbind(paydata1, tot.mean)

tot.mean <- c("tot.mean",tot.mean)
paydata1[,1]

#####display the observations for the teams we are interested in (Boston Red Sox & Oakland A's), plus the first three teams in the dataset.  
paydata1[c(4,20,1,2,3),]

#####boxplots for tot.payroll and avgwin 
boxplot(paydata$payroll)
######WORK IN PROGRESS......trying to put a horizontal line for A's and Red Sox 
  abline(
    h = 0.5487172,
    col = "lightblue",
    lwd = 2 
  )
######END OF WORK IN PROGRESS....... 
boxplot(paydata$avgwin)

#####scatterplot of average by total payroll from 1998 to 2014 
plot(paydata$payroll, paydata$avgwin, 
       pch  = 16, 
       cex  = 1.2,
       col  = "blue",
       xlab = "Payroll", 
       ylab = "Win Percentage",
       main = "MLB Teams's Overall Win Percentage vs. Payroll")

######WORK IN PROGRESS: identify the Oakland A's and Boston Red Sox in the scatterplot. 
identify(paydata$payroll, paydata$avgwin, labels=paydata$team, plot=TRUE) 

####ii) For a given year, is payroll a significant variable to predict the winning percentage of that year? Choose a year and run a regression to examine this. You may try this for a few different years. Explain your results.

  myfit0 <- lm(avgwin~tot.payroll, data=paydata1)
  summary(myfit0)
  
  myfit1998 <- lm(pctwin.1998~payroll.1998, data=paydata1)  
  summary(myfit1998)
  
  myfit2006 <- lm(pctwin.2006~payroll.2006, data=paydata1)  
  summary(myfit2006)
  
  myfit2014 <- lm(pctwin.2014~payroll.2014, data=paydata1)  
  summary(myfit2014)
  
  par(mfrow = c(2,2))
  
    plot(paydata1$tot.payroll, paydata$avgwin, 
       pch  = 16, 
       cex  = 1.2,
       col  = "blue",
       xlab = "Payroll", 
       ylab = "Win Percentage",
       xlim = c(0, 2.5),
       ylim = c(0.4, 0.7),
       main = "MLB Teams's Overall Win Percentage vs. Payroll")
    abline(myfit0, col="red", lwd=4)
    
    plot(paydata1$payroll.1998, paydata1$pctwin.1998, 
       pch  = 16, 
       cex  = 1.2,
       col  = "blue",
       xlab = "Payroll", 
       ylab = "Win Percentage",
       xlim = c(0, 250),
       ylim = c(0.4, 0.7),
       main = "MLB Teams's Win Percentage vs. Payroll in 1998")
    abline(myfit1998, col="red", lwd=4) 

    plot(paydata1$payroll.2006, paydata1$pctwin.2006, 
       pch  = 16, 
       cex  = 1.2,
       col  = "blue",
       xlab = "Payroll", 
       ylab = "Win Percentage",
       xlim = c(0, 250),
       ylim = c(0.4, 0.7),
       main = "MLB Teams's Win Percentage vs. Payroll in 2006")
    abline(myfit2006, col="red", lwd=4) 
  
    plot(paydata1$payroll.2014, paydata1$pctwin.2014, 
       pch  = 16, 
       cex  = 1.2,
       col  = "blue",
       xlab = "Payroll", 
       ylab = "Win Percentage",
       xlim = c(0, 250),
       ylim = c(0.4, 0.7),
       main = "MLB Teams's Win Percentage vs. Payroll in 2014")
    abline(myfit2014, col="red", lwd=4) 
  
####iii) Now use the aggregated information, and use regression to analyze the relation between total payroll and overall winning percentage. Run appropriate model(s) to answer the following questions.
#####a) In this analysis do the Boston Red Sox perform reasonably well given their total payroll? [Use a 95% prediction interval.]

  attach(paydata1)
  
  new <- data.frame(tot.payroll=c(1.972359)) #Boston Red Sox's total payroll 
  CImean <- predict(myfit0, new, interval="prediction", se.fit=TRUE)  
  CImean

######Answer: The Boston Red Sox, with an average of 55% of games won between 1998 and 2014, falls within the confidence interval in terms of their performance given their payroll.

#####b) In view of their winning percentage, how much payroll should the Oakland A’s have spent? [Use a 95% prediction interval.]

  myfit1 <- lm(tot.payroll~avgwin, data=paydata1)
  summary(myfit1)

  new2 <- data.frame(avgwin=c(0.5445067)) #Oakland A's average of games won between 1998 and 2014
    CImean <- predict(myfit1, new2, interval="prediction", se.fit=TRUE)  
    CImean

######Answer: Using the regression model in myfit1, we would have predicted that a team winning 54% of all games between 1998 and 2014 should have a total payroll over that time between 0.95 and 2.27 billion dollars. Given this result, we can say that the Oakland A's performed beyond expectation for their budget. 

#####iv) What is the best model you could build on the basis of this data to capture the important factors affecting winning percentage in 2014 and predict that percentage for 2015? 
##Describe the process of your analysis. What criterion are you using? Report your findings.

  myfit2014 <- lm(pctwin.2014~payroll.2014, data=paydata1)  
  summary(myfit2014)

  attach(paydata1)
  
  new3 <- data.frame(payroll.2014=c(162.8174)) #Boston Red Sox's payroll for 2014
  CImean <- predict(myfit2014, new3, interval="prediction", se.fit=TRUE) #Prediction of Boston Red Sox's performance in 2015 based on the myfit2014 model, and its payroll in 2014 
  CImean
  
######I really don't know whether this is the right way. Please let me know if you have a better idea! 


### Question 5 
